# Generated by Django 5.0.6 on 2024-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhuramkitchen', '0002_category_menuitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
