# Generated by Django 5.0.6 on 2024-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhuramkitchen', '0003_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('title', 'category')},
        ),
    ]
