# Generated by Django 5.0.6 on 2024-06-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhuramkitchen', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='dish_name',
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('dish_name', 'category')},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dish_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('green_leafy', 'Green Leafy Vegetables')], default='veg', max_length=20),
        ),
    ]
